PR for Add notes
manismk/key-notes pull request #6
Opened 2022-03-28 17:39 UTC by manismk

- Added add note functionality
- Read and store data in firebase 
- [Link]()

2022-03-28 18:51 UTC, shraddha-amber requested changes

2022-03-28 18:51 UTC, shraddha-amber commented on src/components/notes-form/NotesForm.jsx
> +                const { error } = handleNotesValidation(
move this logic part into a separate handler function

2022-03-28 18:51 UTC, shraddha-amber commented on src/pages/Profile/Profile.jsx
> +          {user && user ? (
i think this should work by ternary, no need to use user &&

2022-03-28 18:51 UTC, shraddha-amber commented on src/utils/handleNotesValidation.js
> +  if (title.length === 0 && note.length === 0)
instead of multiple if statements, write if-else ladder, or directly return the error from the same if block

2022-03-29 04:55 UTC, manismk commented on src/components/notes-form/NotesForm.jsx
> +                const { error } = handleNotesValidation(
Thanks @shraddha-1402  I have made the changes

2022-03-29 04:55 UTC, manismk commented on src/pages/Profile/Profile.jsx
> +          {user && user ? (
Done

2022-03-29 04:55 UTC, manismk commented on src/utils/handleNotesValidation.js
> +  if (title.length === 0 && note.length === 0)
I have made early return on all the if blocks

2022-03-29 04:59 UTC, shraddha-1402 approved these changes

2022-03-29 05:07 UTC, Pratik1005 approved these changes
Good folder structure and nice UI

2022-03-29 09:37 UTC, merged